# Generated by Django 4.0.2 on 2022-02-03 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='lock_other',
            new_name='enabled_choise',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_points',
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
