# Generated by Django 4.0.2 on 2022-02-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_page', '0002_rename_user_answer_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='visible',
            new_name='unvisible',
        ),
    ]
