# Generated by Django 4.0.2 on 2022-02-05 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_page', '0006_alter_answer_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ip',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
